version: '3.4'

services:
  weatherlivebackend:
    image: weatherlivebackend
    build:
      context: weather-live-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: develepment
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      